In [1]:
steam = pd.read_csv('data/steam.csv')
steam_desc = pd.read_csv('data/steam_description_data.csv')
steam_med = pd.read_csv('data/steam_media_data.csv')
steam_req = pd.read_csv('data/steam_requirements_data.csv')
steam_sup = pd.read_csv('data/steam_support_info.csv')
steam_tag = pd.read_csv('data/steamspy_tag_data.csv')

In [2]:
steam.tail()

appid                        name release_date  english  \
27070  1065230             Room of Pandora   2019-04-24        1   
27071  1065570                   Cyber Gun   2019-04-23        1   
27072  1065650            Super Star Blast   2019-04-24        1   
27073  1066700  New Yankee 7: Deer Hunters   2019-04-17        1   
27074  1069460                   Rune Lord   2019-04-24        1   

                developer             publisher    platforms  required_age  \
27070         SHEN JIAWEI           SHEN JIAWEI      windows             0   
27071      Semyon Maximov      BekkerDev Studio      windows             0   
27072         EntwicklerX           EntwicklerX      windows             0   
27073  Yustas Game Studio  Alawar Entertainment  windows;mac             0   
27074    Adept Studios GD  Alawar Entertainment  windows;mac             0   

                                              categories  \
27070                   Single-player;Steam Achievements   
27071                                      Single-player   
27072  Single-player;Multi-player;Co-op;Shared/Split ...   
27073                          Single-player;Steam Cloud   
27074                          Single-player;Steam Cloud   

                       genres           steamspy_tags  achievements  \
27070  Adventure;Casual;Indie  Adventure;Indie;Casual             7   
27071  Action;Adventure;Indie  Action;Indie;Adventure             0   
27072     Action;Casual;Indie     Action;Indie;Casual            24   
27073  Adventure;Casual;Indie  Indie;Casual;Adventure             0   
27074  Adventure;Casual;Indie  Indie;Casual;Adventure             0   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
27070                 3                 0                 0                0   
27071                 8                 1                 0                0   
27072                 0                 1                 0                0   
27073                 2                 0                 0                0   
27074                 4                 0                 0                0   

        owners  price  
27070  0-20000   2.09  
27071  0-20000   1.69  
27072  0-20000   3.99  
27073  0-20000   5.19  
27074  0-20000   5.19

In [3]:
steam_desc.tail()

steam_appid                               detailed_description  \
27329      1065230  <img src="https://steamcdn-a.akamaihd.net/stea...   
27330      1065570  Have you ever been so lonely that no one but y...   
27331      1065650  <strong>Super Star Blast </strong>is a space b...   
27332      1066700  Pursue a snow-white deer through an enchanted ...   
27333      1069460  A portal has opened and dark magic is pouring ...   

                                          about_the_game  \
27329  <img src="https://steamcdn-a.akamaihd.net/stea...   
27330  Have you ever been so lonely that no one but y...   
27331  <strong>Super Star Blast </strong>is a space b...   
27332  Pursue a snow-white deer through an enchanted ...   
27333  A portal has opened and dark magic is pouring ...   

                                       short_description  
27329  The Room of Pandora is a third-person interact...  
27330  Cyber Gun is a hardcore first-person shooter w...  
27331  Super Star Blast is a space based game with ch...  
27332  Pursue a snow-white deer through an enchanted ...  
27333  A portal has opened and dark magic is pouring ...

In [4]:
steam.tail()

appid                        name release_date  english  \
27070  1065230             Room of Pandora   2019-04-24        1   
27071  1065570                   Cyber Gun   2019-04-23        1   
27072  1065650            Super Star Blast   2019-04-24        1   
27073  1066700  New Yankee 7: Deer Hunters   2019-04-17        1   
27074  1069460                   Rune Lord   2019-04-24        1   

                developer             publisher    platforms  required_age  \
27070         SHEN JIAWEI           SHEN JIAWEI      windows             0   
27071      Semyon Maximov      BekkerDev Studio      windows             0   
27072         EntwicklerX           EntwicklerX      windows             0   
27073  Yustas Game Studio  Alawar Entertainment  windows;mac             0   
27074    Adept Studios GD  Alawar Entertainment  windows;mac             0   

                                              categories  \
27070                   Single-player;Steam Achievements   
27071                                      Single-player   
27072  Single-player;Multi-player;Co-op;Shared/Split ...   
27073                          Single-player;Steam Cloud   
27074                          Single-player;Steam Cloud   

                       genres           steamspy_tags  achievements  \
27070  Adventure;Casual;Indie  Adventure;Indie;Casual             7   
27071  Action;Adventure;Indie  Action;Indie;Adventure             0   
27072     Action;Casual;Indie     Action;Indie;Casual            24   
27073  Adventure;Casual;Indie  Indie;Casual;Adventure             0   
27074  Adventure;Casual;Indie  Indie;Casual;Adventure             0   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
27070                 3                 0                 0                0   
27071                 8                 1                 0                0   
27072                 0                 1                 0                0   
27073                 2                 0                 0                0   
27074                 4                 0                 0                0   

        owners  price  
27070  0-20000   2.09  
27071  0-20000   1.69  
27072  0-20000   3.99  
27073  0-20000   5.19  
27074  0-20000   5.19

In [5]:
steam_1 = pd.merge(steam, steam_desc, how='inner', left_on='appid', right_on='steam_appid')

In [6]:
steam_1 = pd.merge(steam_1, steam_med, how='inner', left_on='appid', right_on='steam_appid')

In [7]:
steam_1 = pd.merge(steam_1, steam_req, how='inner', left_on='appid', right_on='steam_appid')

In [8]:
steam_1 = pd.merge(steam_1, steam_sup, how='inner', left_on='appid', right_on='steam_appid')

In [9]:
steam_1

appid                            name release_date  english  \
0           10                  Counter-Strike   2000-11-01        1   
1           30                   Day of Defeat   2003-05-01        1   
2           50       Half-Life: Opposing Force   1999-11-01        1   
3           70                       Half-Life   1998-11-08        1   
4           80  Counter-Strike: Condition Zero   2004-03-01        1   
...        ...                             ...          ...      ...   
26863  1065230                 Room of Pandora   2019-04-24        1   
26864  1065570                       Cyber Gun   2019-04-23        1   
26865  1065650                Super Star Blast   2019-04-24        1   
26866  1066700      New Yankee 7: Deer Hunters   2019-04-17        1   
26867  1069460                       Rune Lord   2019-04-24        1   

                developer             publisher          platforms  \
0                   Valve                 Valve  windows;mac;linux   
1                   Valve                 Valve  windows;mac;linux   
2        Gearbox Software                 Valve  windows;mac;linux   
3                   Valve                 Valve  windows;mac;linux   
4                   Valve                 Valve  windows;mac;linux   
...                   ...                   ...                ...   
26863         SHEN JIAWEI           SHEN JIAWEI            windows   
26864      Semyon Maximov      BekkerDev Studio            windows   
26865         EntwicklerX           EntwicklerX            windows   
26866  Yustas Game Studio  Alawar Entertainment        windows;mac   
26867    Adept Studios GD  Alawar Entertainment        windows;mac   

       required_age                                         categories  \
0                 0  Multi-player;Online Multi-Player;Local Multi-P...   
1                 0              Multi-player;Valve Anti-Cheat enabled   
2                 0  Single-player;Multi-player;Valve Anti-Cheat en...   
3                 0  Single-player;Multi-player;Online Multi-Player...   
4                 0  Single-player;Multi-player;Valve Anti-Cheat en...   
...             ...                                                ...   
26863             0                   Single-player;Steam Achievements   
26864             0                                      Single-player   
26865             0  Single-player;Multi-player;Co-op;Shared/Split ...   
26866             0                          Single-player;Steam Cloud   
26867             0                          Single-player;Steam Cloud   

                       genres  ... steam_appid_x  \
0                      Action  ...            10   
1                      Action  ...            30   
2                      Action  ...            50   
3                      Action  ...            70   
4                      Action  ...            80   
...                       ...  ...           ...   
26863  Adventure;Casual;Indie  ...       1065230   
26864  Action;Adventure;Indie  ...       1065570   
26865     Action;Casual;Indie  ...       1065650   
26866  Adventure;Casual;Indie  ...       1066700   
26867  Adventure;Casual;Indie  ...       1069460   

                                         pc_requirements  \
0      {'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...   
1      {'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...   
2      {'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...   
3      {'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...   
4      {'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...   
...                                                  ...   
26863  {'minimum': '<strong>Minimum:</strong><br><ul ...   
26864  {'minimum': '<strong>Minimum:</strong><br><ul ...   
26865  {'minimum': '<strong>Minimum:</strong><br><ul ...   
26866  {'minimum': '<strong>Minimum:</strong><br><ul ...   
26867  {'minimum': '<strong>Minimum:</strong><br><ul ...   

                                        mac_requirements  \
0      {

In [10]:
steam_df = steam_1[['name', 'english', 'categories', 'genres', 'short_description']]

In [11]:
steam_df.categories = steam_df.categories.apply(lambda x : x.split(';'))
steam_df['categories_literal'] = steam_df.categories.apply(lambda x : (' ').join(x))
steam_df.genres = steam_df.genres.apply(lambda x : x.split(';'))
steam_df['genres_literal'] = steam_df.genres.apply(lambda x : (' ').join(x))


In [12]:
steam_df.drop(['categories', 'genres'], axis=1, inplace=True)

In [13]:
steam_df

name  english  \
0                      Counter-Strike        1   
1                       Day of Defeat        1   
2           Half-Life: Opposing Force        1   
3                           Half-Life        1   
4      Counter-Strike: Condition Zero        1   
...                               ...      ...   
26863                 Room of Pandora        1   
26864                       Cyber Gun        1   
26865                Super Star Blast        1   
26866      New Yankee 7: Deer Hunters        1   
26867                       Rune Lord        1   

                                       short_description  \
0      Play the world's number 1 online action game. ...   
1      Enlist in an intense brand of Axis vs. Allied ...   
2      Return to the Black Mesa Research Facility as ...   
3      Named Game of the Year by over 50 publications...   
4      With its extensive Tour of Duty campaign, a ne...   
...                                                  ...   
26863  The Room of Pandora is a third-person interact...   
26864  Cyber Gun is a hardcore first-person shooter w...   
26865  Super Star Blast is a space based game with ch...   
26866  Pursue a snow-white deer through an enchanted ...   
26867  A portal has opened and dark magic is pouring ...   

                                      categories_literal  \
0      Multi-player Online Multi-Player Local Multi-P...   
1                  Multi-player Valve Anti-Cheat enabled   
2      Single-player Multi-player Valve Anti-Cheat en...   
3      Single-player Multi-player Online Multi-Player...   
4      Single-player Multi-player Valve Anti-Cheat en...   
...                                                  ...   
26863                   Single-player Steam Achievements   
26864                                      Single-player   
26865  Single-player Multi-player Co-op Shared/Split ...   
26866                          Single-player Steam Cloud   
26867                          Single-player Steam Cloud   

               genres_literal  
0                      Action  
1                      Action  
2                      Action  
3                      Action  
4                      Action  
...                       ...  
26863  Adventure Casual Indie  
26864  Action Adventure Indie  
26865     Action Casual Indie  
26866  Adventure Casual Indie  
26867  Adventure Casual Indie  

[26868 rows x 5 columns]

In [14]:
steam_df['literal'] = steam_df['categories_literal'] + " " + steam_df['genres_literal']

In [15]:
steam_df

name  english  \
0                      Counter-Strike        1   
1                       Day of Defeat        1   
2           Half-Life: Opposing Force        1   
3                           Half-Life        1   
4      Counter-Strike: Condition Zero        1   
...                               ...      ...   
26863                 Room of Pandora        1   
26864                       Cyber Gun        1   
26865                Super Star Blast        1   
26866      New Yankee 7: Deer Hunters        1   
26867                       Rune Lord        1   

                                       short_description  \
0      Play the world's number 1 online action game. ...   
1      Enlist in an intense brand of Axis vs. Allied ...   
2      Return to the Black Mesa Research Facility as ...   
3      Named Game of the Year by over 50 publications...   
4      With its extensive Tour of Duty campaign, a ne...   
...                                                  ...   
26863  The Room of Pandora is a third-person interact...   
26864  Cyber Gun is a hardcore first-person shooter w...   
26865  Super Star Blast is a space based game with ch...   
26866  Pursue a snow-white deer through an enchanted ...   
26867  A portal has opened and dark magic is pouring ...   

                                      categories_literal  \
0      Multi-player Online Multi-Player Local Multi-P...   
1                  Multi-player Valve Anti-Cheat enabled   
2      Single-player Multi-player Valve Anti-Cheat en...   
3      Single-player Multi-player Online Multi-Player...   
4      Single-player Multi-player Valve Anti-Cheat en...   
...                                                  ...   
26863                   Single-player Steam Achievements   
26864                                      Single-player   
26865  Single-player Multi-player Co-op Shared/Split ...   
26866                          Single-player Steam Cloud   
26867                          Single-player Steam Cloud   

               genres_literal  \
0                      Action   
1                      Action   
2                      Action   
3                      Action   
4                      Action   
...                       ...   
26863  Adventure Casual Indie   
26864  Action Adventure Indie   
26865     Action Casual Indie   
26866  Adventure Casual Indie   
26867  Adventure Casual Indie   

                                                 literal  
0      Multi-player Online Multi-Player Local Multi-P...  
1           Multi-player Valve Anti-Cheat enabled Action  
2      Single-player Multi-player Valve Anti-Cheat en...  
3      Single-player Multi-player Online Multi-Player...  
4      Single-player Multi-player Valve Anti-Cheat en...  
...                                                  ...  
26863  Single-player Steam Achievements Adventure Cas...  
26864               Single-player Action Adventure Indie  
26865  Single-player Multi-player Co-op Shared/Split ...  
26866   Single-player Steam Cloud Adventure Casual Indie  
26867   Single-player Steam Cloud Adventure Casual Indie  

[26868 rows x 6 columns]

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(steam_df['literal'])
print(genre_mat.shape)

(26868, 732)


In [17]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(26868, 26868)
[[1.         0.80361438 0.76968257 ... 0.30961158 0.12688648 0.12688648]
 [0.80361438 1.         0.89079867 ... 0.21657404 0.07692308 0.07692308]]


In [18]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
genre_sim_sorted_ind

array([[    0,     3, 24732, ..., 25770, 22783, 25661],
       [    1,     4,     2, ...,  4155,  8272, 25457],
       [    4,     2,    34, ..., 25417,  4912, 16326],
       ...,
       [26865,  5230,  6665, ...,  1880,  5878, 22812],
       [26867, 26842, 26866, ..., 25132, 13162,  5033],
       [26867, 26842, 26866, ..., 25132, 13162,  5033]], dtype=int64)

In [19]:
def find_sim_game(df, sorted_ind, title_name, top_n=10):
    title_game = df[df['name'] == title_name]

    title_index = title_game.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]

    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [20]:
sim_games = find_sim_game(steam_df, genre_sim_sorted_ind, 'Counter-Strike', 10)
sim_games[['name', 'literal']]

[[    0     3 24732   100  1017 17469 13723 17028     1 22790]]


name  \
0                      Counter-Strike   
3                           Half-Life   
24732                        PRATAGON   
100    Cossacks II: Battle for Europe   
1017     Cossacks II: Napoleonic Wars   
17469  Fatal Velocity: Physics Combat   
13723    Shogo: Mobile Armor Division   
17028                 The Broken Seal   
1                       Day of Defeat   
22790               Dragon`s Checkers   

                                                 literal  
0      Multi-player Online Multi-Player Local Multi-P...  
3      Single-player Multi-player Online Multi-Player...  
24732  Single-player Multi-player Online Multi-Player...  
100    Single-player Multi-player Online Multi-Player...  
1017   Single-player Multi-player Online Multi-Player...  
17469  Multi-player Online Multi-Player Local Multi-P...  
13723  Single-player Multi-player Online Multi-Player...  
17028  Single-player Multi-player Online Multi-Player...  
1           Multi-player Valve Anti-Cheat enabled Action  
22790  Single-player Multi-player Online Multi-Player...